twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        '%kernel.project_dir%/public/assets/images': images
        '%kernel.project_dir%/public/uploads': downloadedimages
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
